services:
  postgres:
    container_name: postgres_db
    image: postgres:17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always