# Generated by Django 5.2.6 on 2025-09-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Importe')),
                ('is_created_auto', models.BooleanField(default=True)),
                ('is_updated_auto', models.BooleanField(default=True)),
                ('created_manual', models.DateField(blank=True, null=True)),
                ('updated_manual', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
